# Generated by Django 5.2.6 on 2025-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('temp_current', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('rh_current', models.FloatField(blank=True, null=True)),
                ('rh_min', models.FloatField(blank=True, null=True)),
                ('rh_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'db_table': 'monitoring_measurement',
                'ordering': ['ts'],
                'get_latest_by': 'ts',
                'indexes': [models.Index(fields=['ts'], name='mm_ts_idx')],
            },
        ),
    ]
